
FROM ubuntu:14.04

RUN apt-get -y --force-yes update

RUN apt-get install -y --force-yes \

sudo apt-get install software-properties-common python-software-properties
sudo add-apt-repository ppa:ubuntu-toolchain-r/test

sudo apt-get -y --force-yes update
sudo apt-get isntall git
